modLoader="javafml"
loaderVersion="[47,)"
license="GNU Affero General Public License v3.0"
issueTrackerURL="https://github.com/Moirstral/AutoTranslation/issues"

[[mods]]
modId="autotranslation"
version="${file.jarVersion}"
displayName="AutoTranslation"
authors="墨涤千尘"
displayURL="https://github.com/Moirstral/AutoTranslation"
displayTest="IGNORE_SERVER_VERSION"
description='''Client-side automatic translation for missing language keys.'''

[[dependencies.autotranslation]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.autotranslation]]
modId="cloth_config"
mandatory=true
versionRange="[11.1.118,12)"
ordering="NONE"
side="CLIENT"

[[dependencies.autotranslation]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"
